paytm/urls.py
from django.urls import path
from paytm import views
app_name = 'paytm'

urlpatterns = [
    # path('home/', views.Home.as_view(), name='home'),
    path('', views.home, name='home-paytm'),
    path('payment/', views.payment, name='payment'),
    path('response/', views.response, name='response'),
]

shop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('textiles.urls')),
    path('', include('accounts.urls')),
    # path('oauth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
    path('paytm/', include('paytm.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

textiles/urls.py
from django.urls import path
from textiles import views
app_name = 'textiles'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('saree/', views.IndexList.as_view(), name='saree'),
    path('saree/<int:pk>/', views.saree_detail.as_view(), name='saree_detail'),
    path('cart/', views.cart_view, name='cart'),
    path('<int:pk>/buy/', views.buy_view, name='buy'),
    path('order/<int:pk>/delete/', views.OrderDelete.as_view(), name='deleteorder'),
    path('payment/', views.payment, name='payment'),
    path('response/', views.response, name='response'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    
    
    # path('', views.home, name='home-paytm'),
    # path('payment/', views.payment, name='payment'),
    # path('response/', views.response, name='response'),
]

textiles/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
# Create your models here.

class Address(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    address = models.CharField(max_length=500)
    address_line1 = models.CharField(max_length=500)
    address_line2 = models.CharField(max_length=500)
    contact = models.CharField(max_length=10)
    pincode = models.IntegerField()



class Product(models.Model):
    INSTANT = 0
    IN_DAYS = 1
    IN_A_WEEK = 2
    IN_A_MONTH = 3
    
    YEAR_IN_SCHOOL_CHOICES = (
        (INSTANT, 'Instant'),
        (IN_DAYS, 'In 1-2 Days'),
        (IN_A_WEEK, 'In 7-8 Days'),
        (IN_A_MONTH, 'In 30 days'),
    )
    
    SMALL = "S"
    MEDIUM = "M"
    LARGE = "L"
    EXTRA_LARGE = "XL"
    DOUBLE_EXTRA_LARGE = "XXL"
    TRIPLE_EXTRA_LARGE = "XXXL"
    
    
    SIZE_CHOICES = (
        (SMALL, "S"),
        (MEDIUM, 'M'),
        (LARGE, "L"),
        (EXTRA_LARGE, "XL"),
        (DOUBLE_EXTRA_LARGE, "XXL"),
        (TRIPLE_EXTRA_LARGE, "XXXL"),
        
    )
    SEMI_STICHED = "SS"
    STICHED = "S"
    UNSTICHED = "US"
    
    
    
    STICHING_CHOICES = (
        (SEMI_STICHED, "SS"),
        (STICHED, "S"),
        (UNSTICHED, "US"),
        
    )
    product_name = models.CharField(max_length=500)
    product_id = models.CharField(max_length=100)
    product_type = models.CharField(max_length=100)
    product_detail = models.CharField(max_length = 5000)
    length = models.DecimalField(max_digits=5, decimal_places=4, blank=True, null=True)
    size = models.CharField(choices=SIZE_CHOICES, max_length=100, null=True, blank=True)
    category = models.CharField(max_length=100)
    color = models.CharField(max_length=50, blank=True, null=True)
    stiched_type = models.CharField(choices=STICHING_CHOICES, max_length=100, null=True, blank=True)
    material = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    discount_rate = models.DecimalField(max_digits=5, decimal_places=4)
    discount_percent = models.IntegerField()
    stock_balance = models.PositiveIntegerField()
    dispatch_in = models.PositiveIntegerField(choices=YEAR_IN_SCHOOL_CHOICES, null=True, blank=True)
    free_shipping = models.BooleanField(default=False)
    care = models.CharField(max_length=100)
    

    def __str__(self):
        return self.product_name

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='product_image', on_delete=models.CASCADE)
    image = models.ImageField()
    label = models.CharField(max_length=100)

    def __str__(self):
        return self.label


class SubProduct(models.Model):
    product = models.ForeignKey(Product, related_name='sub_product', on_delete=models.CASCADE)
    sub_product_name = models.CharField(max_length=500)
    material = models.CharField(max_length=100)
    length = models.DecimalField(max_digits=5, decimal_places=4)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.sub_product_name 


class Order(models.Model):
    ordered_by = models.ForeignKey(User, related_name='orderer', on_delete=models.CASCADE)
    order_id = models.CharField(max_length=10, null=True, blank=True)
    order_date = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, related_name='ordered_product', on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.order_id
    



class PaytmHistory(models.Model):
    user = models.ForeignKey(User, related_name='rel_payment_paytm', on_delete=models.CASCADE, null=True, blank=True)
    ORDERID = models.CharField('ORDER ID', max_length=30)
    TXNDATE = models.CharField('TXN DATE', max_length=250)
    TXNID = models.CharField('TXN ID', max_length=500)
    BANKTXNID = models.CharField('BANK TXN ID', max_length=500, null=True, blank=True)
    BANKNAME = models.CharField('BANK NAME', max_length=50, null=True, blank=True)
    RESPCODE = models.CharField('RESP CODE', max_length=500)
    PAYMENTMODE = models.CharField('PAYMENT MODE', max_length=10, null=True, blank=True)
    CURRENCY = models.CharField('CURRENCY', max_length=4, null=True, blank=True)
    GATEWAYNAME = models.CharField("GATEWAY NAME", max_length=30, null=True, blank=True)
    MID = models.CharField(max_length=40)
    RESPMSG = models.TextField('RESP MSG', max_length=250)
    TXNAMOUNT = models.FloatField('TXN AMOUNT')
    STATUS = models.CharField('STATUS', max_length=12)


    # class Meta:
    #     app_label = 'paytm'

    def __str__(self):
        return self.STATUS

textiles/views.py
from django.conf import settings
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.utils.translation import get_language
from django.views.decorators.csrf import csrf_exempt
from textiles.models import Product, ProductImage, Order
from django.views.generic.base import TemplateView, View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from textiles import Checksum
from textiles.models import Order, PaytmHistory


# Create your views here.

# def home(request):
#     return render(request, 'textiles/home.html', {})

class Home(TemplateView):
    template_name = 'textiles/home.html'

class IndexList(View):
    template_name = 'textiles/saree.html'
    queryset = Product.objects.filter(product_type="Saree")

    def get_queryset(self):
        return self.queryset

    def get(self, request, *args, **kwargs):
        image = ProductImage.objects.get(product=self.queryset[0])
        context = { 'object_list': self.get_queryset, 'image': image   }
        return render(request, self.template_name, context)

class saree_detail(View):
    template_name = 'textiles/saree_detail.html'

    def get_object(self):
        id = self.kwargs.get('pk')
        obj= None
        if id is not None:
            obj = get_object_or_404(Product, id=id)
        return obj
    
    def get(self, request, *args, **kwargs):
        image = ProductImage.objects.get(product=self.get_object())
        context = { 'saree': self.get_object(), 'image': image }
        # ordered_by = request.user
        # order_id = paytm.Checksum.__id_generator__()
        # product = self.get_object()
        # Order.objects.create(ordered_by=ordered_by, order_id=order_id, product=product)
        return render(request, self.template_name, context)

    
def buy_view(request, pk, **kwargs):
    context = {}
    # id = request.kwargs.get('pk')
    obj= None
    if id is not None:
        obj = get_object_or_404(Product, id=pk)
    ordered_by = request.user
    # order_id = Checksum.__id_generator__()
    product = obj
    Order.objects.create(ordered_by=ordered_by, product=product)
    return redirect('textiles:cart')
        
        
def cart_view(request, *args, **kwargs):
    user = request.user 
    checkout_price=0
    # image = ProductImage.objects.get(product=self.get_object())
    incart = Order.objects.filter(ordered_by=user, is_active=True)
    # request.session['user'] = user
    for order in incart:    
        checkout_price += order.product.price
        try:
            image = ProductImage.objects.get(product=order.product)
        except:
            pass
    
    total = checkout_price
    try:
        images = image
    except:
        pass
    return render(request, 'textiles/cart.html', {'cart': incart, 'total': total, 'image': images})


class OrderDelete(View):
    template_name = 'textiles/order_confirm_delete.html'

    def get_object(self):
        id = self.kwargs.get('pk')
        obj= None
        if id is not None:
            obj = get_object_or_404(Order, id=id)
        return obj

    def get(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            context['object'] = obj
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            obj.delete()
            context['object'] = None
            return redirect('textiles:cart')
        return render(request, self.template_name, context) 

def payment(request):
    MERCHANT_KEY = settings.PAYTM_MERCHANT_KEY
    MERCHANT_ID = settings.PAYTM_MERCHANT_ID
    get_lang = "/" + get_language() if get_language() else ''
    CALLBACK_URL = settings.HOST_URL + get_lang + settings.PAYTM_CALLBACK_URL
    # import pdb; pdb.set_trace()
    user = request.user
    cust_id = user.username
    checkout_price=0
    # Generating unique temporary ids
    order_id = Checksum.__id_generator__()
    incart = Order.objects.filter(ordered_by=user, is_active=True)
    for order in incart:    
        checkout_price += order.product.price
        order.order_id = order_id
        order.save()
    total = checkout_price
    
    
    
    
    # import pdb; pdb.set_trace()
    bill_amount = 100
    if bill_amount:
        data_dict = {
                    'MID':MERCHANT_ID,
                    'ORDER_ID':order_id,
                    'TXN_AMOUNT': bill_amount,
                    'CUST_ID':cust_id,
                    'INDUSTRY_TYPE_ID':'Retail',
                    'WEBSITE': settings.PAYTM_WEBSITE,
                    'CHANNEL_ID':'WEB',
                    'CALLBACK_URL':'http://colourplus.live/response/',
                }
        param_dict = data_dict
        param_dict['CHECKSUMHASH'] = Checksum.generate_checksum(data_dict, MERCHANT_KEY)
        return render(request,"paytm/payment.html",{'paytmdict':param_dict, 'orderid': order_id })
    return HttpResponse("Bill Amount Could not find. ?bill_amount=10")


@csrf_exempt
def response(request):
    if request.method == "POST":
        MERCHANT_KEY = settings.PAYTM_MERCHANT_KEY
        data_dict = {}
        for key in request.POST:
            data_dict[key] = request.POST[key]
        verify = Checksum.verify_checksum(data_dict, MERCHANT_KEY, data_dict['CHECKSUMHASH'])
        if verify:
            PaytmHistory.objects.create(**data_dict)
            incart = Order.objects.filter(order_id=data_dict['ORDERID'], is_active=True)
            for order in incart:
                order.is_active = False
                order.save()
            return render(request,"paytm/response.html",{"paytm":data_dict})

        else:
            return HttpResponse("checksum verify failed")
    return HttpResponse(status=200)

templates/textiles/cart.html
{% extends 'textiles/base.html' %}{% load static %}
{% block title %}Colour Plus{% endblock %}

{% block style %}
<style>
.table>tbody>tr>td, .table>tfoot>tr>td{
    vertical-align: middle;
}
@media screen and (max-width: 600px) {
    table#cart tbody td .form-control{
		width:20%;
		display: inline !important;
	}
	.actions .btn{
		width:36%;
		margin:1.5em 0;
	}
	
	.actions .btn-info{
		float:left;
	}
	.actions .btn-danger{
		float:right;
	}
	
	table#cart thead { display: none; }
	table#cart tbody td { display: block; padding: .6rem; min-width:320px;}
	table#cart tbody tr td:first-child { background: #333; color: #fff; }
	table#cart tbody td:before {
		content: attr(data-th); font-weight: bold;
		display: inline-block; width: 8rem;
	}
	
	
	
	table#cart tfoot td{display:block; }
	table#cart tfoot td .btn{display:block;}
	
}
</style>
{% endblock %}
{% block stylesheet %}
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock %}
{% block body %}

<div class="container">
        <table id="cart" class="table table-hover table-condensed">
                        <thead>
                            <tr>
                                <th style="width:50%">Product</th>
                                <th style="width:10%">Price</th>
                                <th style="width:8%">Quantity</th>
                                <th style="width:22%" class="text-center">Subtotal</th>
                                <th style="width:10%"></th>
                            </tr>
                        </thead>
                        {% for order in cart %}
                        <tbody>
                            <tr>
                                <td data-th="Product">
                                    <div class="row">
                                        <div class="col-sm-2 hidden-xs"><img src="{{image.image.url}}" alt="..." class="img-responsive"/></div>
                                        <div class="col-sm-10">
                                            <div class="container-fluid">
                                            <h4 class="nomargin">{{order.product.product_name}}</h4>
                                            <p></p>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td data-th="Price">Rs {{order.product.price}}</td>
                                <td data-th="Quantity">
                                    <input type="number" class="form-control text-center" value="1">
                                </td>
                                <td data-th="Subtotal" class="text-center">{{order.product.price}}</td>
                                <td class="actions" data-th="">
                                    <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
                                    <a class="btn btn-danger btn-sm" href='{% url "textiles:deleteorder" order.pk %}'>remove</a>			
                                </td>
                            </tr>
                        </tbody>
                        {% endfor %}
                        <tfoot>
                            
                            <tr>
                                <td><a href="#" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
                                <td colspan="2" class="hidden-xs"></td>
                                <td class="hidden-xs text-center"><strong>{{total}}</strong></td>
                                <td><a href="{% url "textiles:payment" %}" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
                            </tr>
                        </tfoot>
                    </table>
    </div>

{% block script %}

{% endblock %}


{% endblock body %}



-- <h1>success</h1>
{% for order in cart %}
{{order.product.product_name}} -  {{order.product.price}}<a href='{% url "textiles:deleteorder" order.pk %}'>remove</a><br>
{% endfor %}
<h3><a href='{% url "paytm:payment" %}'>Checkout - Rs {{total}}</a></h3> -->

templates/textiles/dashboard.html
{% extends 'textiles/base.html' %} {% load static %}
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}
{%block body%}
<div class="sidenav">
  <a href="#">Boutiques</a>
  <a href="#">Insights</a>
  <a href="#">Settings</a>
  <a href="#">Reviews</a>
</div>



   
{% endblock%}

templates/textiles/order_confirm_delete.html
{% extends 'textiles/base.html' %}

{% block breadcrumb %}
{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

templates/textiles/order_created.html
<h1>order created</h1>

templates/textiles/saree.html
{% extends 'textiles/base.html' %}{% load static %}
{% block title %}Colour Plus{% endblock %}

{% block style %}<style></style>{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block body %}
<div class="container" style="padding-top: 15px;">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active"><a href="{% url "textiles:saree" %}">Saree</a></li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-3">
            <div class="card bg-light mb-3">
                <div class="card-header bg-primary text-white text-uppercase"><i class="fa fa-list"></i> Categories</div>
                <ul class="list-group category_block">
                    <li class="list-group-item"><a href="category.html">Saree</a></li>
                    <li class="list-group-item"><a href="category.html">Lehenga</a></li>
                    <li class="list-group-item"><a href="category.html">Salwar Suits</a></li>
                    <li class="list-group-item"><a href="category.html">Tunics&Kurti</a></li>
                    <li class="list-group-item"><a href="category.html">Western</a></li>
                </ul>
            </div>
            <!-- <div class="card bg-light mb-3">
                <div class="card-header bg-success text-white text-uppercase">Last product</div>
                <div class="card-body">
                    <img class="img-fluid" src="https://dummyimage.com/600x400/55595c/fff" />
                    <h5 class="card-title">Product title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <p class="bloc_left_price">99.00 $</p>
                </div>
            </div> -->
        </div>
        <div class="col">
            <div class="row">
                {% for saree in object_list %}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card">
                        <img class="card-img-top" src="{{image.image.url}}" alt="Card image cap">
                        <div class="card-body" style="padding: 0.60rem;">
                            <h4 class="card-title"><a href="{% url 'textiles:saree_detail' saree.id %}" title="View Product">{{saree.product_name}}</a></h4>
                            <p class="card-text">{{saree.product_detail}}</p>
                            <div class="row">
                                <div class="col">
                                    <p class="btn btn-danger btn-block">Rs {{saree.price}}</p>
                                </div>
                                <div class="col">
                                    <a href="#" class="btn btn-success btn-block">Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                
               



                <div class="col-12" style="padding-top: 50px;">
                    <nav aria-label="...">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active">
                                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

    </div>
</div>



{% block script %}

{% endblock %}


{% endblock body %}




<!-- {% for saree in object_list %}

<h1><a href="{% url 'textiles:saree_detail' saree.id %}">{{saree.product_name}}</a></h1>

{% endfor %} -->

templates/textiles/saree_detail.html
{% extends 'textiles/base.html' %}{% load static %}
{% block title %}Colour Plus{% endblock %}

{% block style %}
<style>

/*****************globals*************/
body {
  font-family: 'open sans';
  overflow-x: hidden; }

img {
  max-width: 100%; }

.preview {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

.preview-pic {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.preview-thumbnail.nav-tabs {
  border: none;
  margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
    .preview-thumbnail.nav-tabs li img {
      max-width: 100%;
      display: block; }
    .preview-thumbnail.nav-tabs li a {
      padding: 0;
      margin: 0; }
    .preview-thumbnail.nav-tabs li:last-of-type {
      margin-right: 0; }

.tab-content {
  overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
            animation-name: opacity;
    -webkit-animation-duration: .3s;
            animation-duration: .3s; }

.card {
  margin-top: 50px;
  /* background: #eee; */
  padding: 3em;
  line-height: 1.5em; }

@media screen and (min-width: 997px) {
  .wrapper {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; } }

.details {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }

.colors {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.product-title, .price, .sizes, .colors {
  text-transform: UPPERCASE;
  font-weight: bold; }

.checked, .price span {
  color: #ff9f1a; }

.product-title, .rating, .product-description, .price, .vote, .sizes {
  margin-bottom: 15px; }

.product-title {
  margin-top: 0; }

.size {
  margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

.color {
  display: inline-block;
  vertical-align: middle;
  margin-right: 10px;
  height: 2em;
  width: 2em;
  border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

.add-to-cart, .like {
  background: #ff9f1a;
  padding: 1.2em 1.5em;
  border: none;
  text-transform: UPPERCASE;
  font-weight: bold;
  color: #fff;
  -webkit-transition: background .3s ease;
          transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: #b36800;
    color: #fff; }

.not-available {
  text-align: center;
  line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

.orange {
  background: #ff9f1a; }

.green {
  background: #85ad00; }

.blue {
  background: #0076ad; }

.tooltip-inner {
  padding: 1.3em; }

@-webkit-keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

@keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

/*# sourceMappingURL=style.css.map */
</style>
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block body %}
<div class="container" style="padding-top: 15px;">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                  <li class="breadcrumb-item active"><a href="{% url "textiles:saree" %}">Saree</a></li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="card">
        <div class="container-fliud">
            <div class="wrapper row">
                <div class="preview col-md-6">
                    
                    <div class="preview-pic tab-content">
                      <div class="tab-pane active" id="pic-1"><img src="{{image.image.url}}" style="max-height: 550px" /></div>
                      <div class="tab-pane" id="pic-2"><img src="{{image.image.url}}" style="max-height: 550px"/></div>
                      <div class="tab-pane" id="pic-3"><img src="{{image.image.url}}" style="max-height: 550px"/></div>
                      <div class="tab-pane" id="pic-4"><img src="{{image.image.url}}" style="max-height: 550px"/></div>
                      <div class="tab-pane" id="pic-5"><img src="{{image.image.url}}" style="max-height: 550px"/></div>
                    </div>
                    <ul class="preview-thumbnail nav nav-tabs">
                      <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="{{image.image.url}}" /></a></li>
                      <li><a data-target="#pic-2" data-toggle="tab"><img src="{{image.image.url}}" style="max-height: 100px;" /></a></li>
                      <li><a data-target="#pic-3" data-toggle="tab"><img src="{{image.image.url}}" style="max-height: 100px;" /></a></li>
                      <li><a data-target="#pic-4" data-toggle="tab"><img src="{{image.image.url}}" style="max-height: 100px;" /></a></li>
                      <li><a data-target="#pic-5" data-toggle="tab"><img src="{{image.image.url}}" style="max-height: 100px;" /></a></li>
                    </ul>
                    
                </div>
                <div class="details col-md-6">
                    <h3 class="product-title">{{saree.product_name}}</h3>
                    <div class="rating">
                        <div class="stars">
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                        </div>
                        <span class="review-no">41 reviews</span>
                    </div>
                    <p class="product-description">{{saree.product_detail}}</p>
                    <h4 class="price">current price: <span>Rs {{saree.price}}</span></h4>
                    <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
                    <a href="{% url 'textiles:buy' saree.pk %}" class="btn btn-success btn-block">Buy Now</a>
                </div>
            </div>
        </div>
    </div>
</div>



{% block script %}

{% endblock %}


{% endblock body %}